[package]
name = "three_body"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
env_logger = "0.10.1"
log = "0.4.20"
nalgebra = "0.32.3"
wgpu = "0.18.0"
winit = "0.29.4"
cfg-if = "1"


[lib]
crate-type = ["cdylib", "rlib"]